providers = ["python", "node"]

[phases.install]
cmds = [
  "python3 -m ensurepip --upgrade",
  "python3 -m pip install -r oracle/requirements.txt",
  "npm install --legacy-peer-deps"
]

[phases.build]
cmds = []
