// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title SolvencyVerifier
/// @notice Verifies ZK solvency proofs generated by the DotLend Noir circuit.
///
/// IMPORTANT — PolkaVM deployment note:
///   This contract is the interface-compatible wrapper for the Noir UltraHonk
///   verifier. The Noir-generated verifier uses inline assembly ONLY for:
///     - BN254 elliptic curve operations (via EVM precompiles 0x06/0x07/0x08)
///     - Gas-optimized field arithmetic
///   These are standard EVM precompile calls, not arbitrary assembly.
///   Assembly blocks are auto-generated by Noir/barretenberg and not hand-written.
///
/// CIRCUIT: circuits/solvency/src/main.nr
/// Proving system: UltraHonk (Noir 1.0.0-beta.19 default)
///
/// Public inputs layout (uint256[] calldata publicInputs):
///   [0] total_collateral_value  -- sum of all user collateral values (USDH-wei)
///   [1] total_debt              -- sum of all user debts (USDH-wei)
///   [2] oracle_timestamp        -- UNIX timestamp of price snapshot used
///
/// @dev For local hardhat tests, deploy MockSolvencyVerifier instead.
///      For Polkadot Hub TestNet, deploy this contract after confirming
///      BN254 precompile availability (ecAdd/ecMul/ecPairing at 0x06-0x08).

interface IUltraHonkVerifier {
    function verify(bytes calldata proof, bytes32[] calldata publicInputs) external view returns (bool);
}

contract SolvencyVerifier {
    /// @notice The UltraHonk verifier generated by Noir/barretenberg
    /// @dev Set at deploy time — cannot be changed after construction
    IUltraHonkVerifier public immutable honkVerifier;

    /// @param _honkVerifier Address of the Noir-generated UltraHonk verifier contract
    constructor(address _honkVerifier) {
        require(_honkVerifier != address(0), "SolvencyVerifier: zero verifier");
        honkVerifier = IUltraHonkVerifier(_honkVerifier);
    }

    /// @notice Verify a ZK solvency proof
    /// @param proof    Raw proof bytes from Noir/barretenberg
    /// @param publicInputs [total_collateral_value, total_debt, oracle_timestamp]
    /// @return true if proof is valid, false otherwise
    function verifySolvency(
        bytes calldata proof,
        uint256[] calldata publicInputs
    ) external view returns (bool) {
        require(publicInputs.length == 3, "SolvencyVerifier: wrong input count");

        // Convert uint256[] to bytes32[] for the UltraHonk verifier
        bytes32[] memory inputs = new bytes32[](3);
        inputs[0] = bytes32(publicInputs[0]);
        inputs[1] = bytes32(publicInputs[1]);
        inputs[2] = bytes32(publicInputs[2]);

        return honkVerifier.verify(proof, inputs);
    }
}
